name: Build installer for supported os
on: push

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - run: mvn -B install